## Client Installation

To deploy applications to OpenShift and manage them, OpenShift provides a
feature rich web console, as well as a command line tool. The OpenShift
command line client is a single executable called `oc`, written in the Go
programming language. The command line client is available for the
following operating systems:

- Microsoft Windows
- Apple OS X
- Linux

This workshop will be using both the web console and command line client.
You therefore need to download the command line client and install it,
such that it is accessible from the executable search path of your command
shell.

### Downloading the client

Download the appropriate client for your operating system using the
following links:

- {{DOWNLOAD_CLIENT_WINDOWS}}[Microsoft Windows]
- {{DOWNLOAD_CLIENT_MACOSX}}[Apple OS X]
- {{DOWNLOAD_CLIENT_LINUX_64BIT}}[Linux (64 Bit)]

Once the file has been downloaded, you will need to extract the contents as
it is a compressed archive. Put the archive and the extracted `oc` executable
file in the following directory:

**Windows:**

[source]
----
C:\OpenShift
----

**OS X:**

[source]
----
~/OpenShift
----

**Linux:**

[source]
----
~/OpenShift
----

Use the following instructions to extract the _oc_ executable file and add
it your executable search path.

### Extracting the tools

Once downloaded, extract the contents of the archive as follows:

**Windows:**

To extract the zip archive on windows, you will need a zip utility
installed on your system. With newer versions of windows (greater than XP),
this is provided by the operating system. Right click on the downloaded
file using *File Explorer* and select the menu option to extract the
contents.

**OS X:**

Open up a terminal window and change to the directory where you downloaded
the file. Once you are in the directory, enter in the following command:

[source,role=copypaste]
----
$ unzip openshift-origin-client-tools-??????-mac.zip
----

**Linux:**

Open up a terminal window and change to the directory where you downloaded the
file.  Once you are in the directory, enter in the following command:

[source]
----
$ tar -xvz --strip-components 1 -f openshift-origin-client-tools-??????-linux-64bit.tar.gz
----

#### Adding `oc` to your PATH

**Windows:**

Because changing your PATH on windows varies by version of the operating system,
we will not list each operating system here.  However, the general workflow is
right click on your computer name inside of the file explorer.  Select Advanced
system settings. I guess changing your PATH is considered an advanced task? :)
Click on the advanced tab, and then finally click on Environment variables.
Once the new dialog opens, select the Path variable and add ";C:\OpenShift" at
the end.  For an easy way out, you could always just copy it to C:\Windows or a
directory you know is already on your path. For more detailed instructions:

https://support.microsoft.com/en-us/kb/310519[Windows XP]

http://banagale.com/changing-your-system-path-in-windows-vista.htm[Windows Vista]

http://geekswithblogs.net/renso/archive/2009/10/21/how-to-set-the-windows-path-in-windows-7.aspx[Windows 7]

http://www.itechtics.com/customize-windows-environment-variables/[Windows 8]

Windows 10 - Follow the directions above.

**OS X:**

[source]
----
$ export PATH=$PATH:~/OpenShift
----

**Linux:**

[source]
----
$ export PATH=$PATH:~/OpenShift
----

#### Verify
At this point, we should have the oc tool available for use.  Let's test this
out by printing the version of the oc command:

[source]
----
$ oc version
----

You should see the following (or something similar):

[source]
----
{{OC_VERSION}}
----

If you get an error message, you have not updated your path correctly.  If you
need help, raise your hand and the instructor will assist.
