## Deploy Application

The Python web application you are going to deploy in this workshop is a
small blog site implemented using the Django web framework.

The source code for the application can be found in the Git repository on
GitHub at:

*link:https://github.com/openshift-katacoda/blog-django-py[]*

You will deploy the application using the Python S2I builder image which is
bundled with OpenShift. It is possible to use either the web console or the
command line client to deploy the application. For this exercise you will
be using the command line.

### Creating the application

To deploy the sample application from the command line run the command:

[source]
----
oc new-app python~https://github.com/openshift-katacoda/blog-django-py --name blog
----

We use the `--name` option so we can override the name for the resources
which are created for the application. If the `--name` option was not used
it would have used `blog-django-py`, being the name of the Git repository.

The output from running the command should be similar to:

[source]
----
--> Found image c918544 (7 days old) in image stream "openshift/python" under tag "3.5" for "python"

    Python 3.5
    ----------
    Platform for building and running Python 3.5 applications

    Tags: builder, python, python35, rh-python35

    * A source build using source code from https://github.com/openshift-katacoda/blog-django-py will be created
      * The resulting image will be pushed to image stream "blog:latest"
      * Use 'start-build' to trigger a new build
    * This image will be deployed in deployment config "blog"
    * Port 8080/tcp will be load balanced by service "blog"
      * Other containers can access this service through the hostname "blog"

--> Creating resources ...
    imagestream "blog" created
    buildconfig "blog" created
    deploymentconfig "blog" created
    service "blog" created
--> Success
    Build scheduled, use 'oc logs -f bc/blog' to track its progress.
    Run 'oc status' to view your app.
----

In this case we did not specify a specific Python version, so it used the
latest version supported by the environment, which was Python 3.5. You can
specify that a specific Python version should be used, such as Python 2.7,
in the `oc new-app` command. Instead of just `python`, you would specify
`python:2.7`.

### Monitoring the build process

To see the list of resources which are created for the application run
the command:

[source]
----
oc get all
----

This will display a list similar to:

[source]
----
NAME      TYPE      FROM      LATEST
bc/blog   Source    Git       1

NAME            TYPE      FROM          STATUS    STARTED         DURATION
builds/blog-1   Source    Git@fcdc38c   Running   6 seconds ago

NAME      DOCKER REPO                           TAGS      UPDATED
is/blog   172.30.1.1:5000/project-user00/blog

NAME      REVISION   DESIRED   CURRENT   TRIGGERED BY
dc/blog   0          1         0         config,image(blog:latest)

NAME       CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
svc/blog   172.30.212.64   <none>        8080/TCP   8s

NAME              READY     STATUS    RESTARTS   AGE
po/blog-1-build   1/1       Running   0          8s
----

The resources hold information such as how to build the application source
code, the location of the image created and how to deploy it.

To view a summary of a specific resource, you can use the `oc describe`
command. For example, to view the build configuration run the command:

[source]
----
oc describe bc/blog
----

This will display output similar to:

[source]
----
Name:           blog
Namespace:      project-user00
Created:        11 seconds ago
Labels:         app=blog
Annotations:    openshift.io/generated-by=OpenShiftNewApp
Latest Version: 1

Strategy:       Source
URL:            https://github.com/openshift-katacoda/blog-django-py
From Image:     ImageStreamTag openshift/python:3.5
Output to:      ImageStreamTag blog:latest

Build Run Policy:       Serial
Triggered by:           Config, ImageChange
Webhook GitHub:
        URL:    https://localhost:8443/oapi/v1/namespaces/project-user00/buildconfigs/blog/webhooks/YyKz-gEjFJ9HKL-mRJC6/github
Webhook Generic:
        URL:            https://localhost:8443/oapi/v1/namespaces/project-user00/buildconfigs/blog/webhooks/rslDLLUiZiwcKXFsc02i/generic
        AllowEnv:       false

Build   Status          Duration        Creation Time
blog-1  running         running for 8s  2017-05-04 11:10:03 +1000 AEST

No events.
----

The resource `builds/blog-1` in the above list of resources corresponds to
the build which is currently running to build an image from the source code
of the application. You can see that it is still running in the summary of
the build configuration for the application.

To monitor the build process and see what is being done, run the command:

[source]
----
oc logs builds/blog-1 --follow
----

This will display output starting out with:

[source]
----
Cloning "https://github.com/openshift-katacoda/blog-django-py" ...
        Commit: fcdc38c5448596f772e337cf847d3bff3408b820 (Change default colour to match OpenShift red.)
        Author: Graham Dumpleton <Graham.Dumpleton@gmail.com>
        Date:   Fri Mar 31 18:22:24 2017 +1100
-----> Running application assemble script.
-----> Running /opt/app-root/src/.s2i/action_hooks/pre_build
-----> Initial environment variables set by builder image.
MANPATH=/opt/rh/rh-python35/root/usr/share/man:/opt/rh/httpd24/root/usr/share/man:
HOSTNAME=blog-1-build
PIP_NO_CACHE_DIR=off
OPENSHIFT_BUILD_COMMIT=fcdc38c5448596f772e337cf847d3bff3408b820
OPENSHIFT_BUILD_NAME=blog-1
LIBRARY_PATH=/opt/rh/httpd24/root/usr/lib64
PYTHONUNBUFFERED=1
....
----

In the log output you will see how the Python S2I builder will pull down
the application source code from the Git repository, install any Python
packages listed in the Python `requirements.txt` file and prepare the
application image to be deployed.

### Triggering a new build

For this workshop, you are deploying the Python web application from an
existing Git repository and cannot change the source code. If this was your
own application, or you had forked the Git repository on GitHub before
starting, you would be able to make updates.

After you make any updates you can trigger a new build and deployment of
the application by running the command:

[source]
----
oc start-build blog
----

This will display output:

[source]
----
build "blog-2" started
----

This will cause the latest application source code to be pulled down from
the Git repository, built into a new image and deployed.

Although not covered in this workshop, you can automate builds and
deployments by registering the GitHub Webhook displayed when you ran `oc
describe` on the build configuration with the Git repository on GitHub.
After the webhook has been registered, any push of new code up to the Git
repository on GitHub will automatically trigger a new build and deployment.

If you wish to iterate on code changes in a local directory, prior to
commiting and pushing them up to a Git repository, it is also possible to
start a new build, but where rather than the application source code being
pulled down from the Git repository, it is taken from a local directory on
your computer.

If you would like to know more about setting up automated builds, or
building from local source code, ask the instructor or workshop assistants
when you have completed the workshop and if time is still available we can
provide more details on how to do it. Further information can also be
found in the online documentation for OpenShift.
